[package]
authors = ["IsaMorphic <me@isamorphic.dev>"]
build = "build.rs"
name = "quiche-bindgen"
version = "0.24.5"
edition = "2021"
links = "quiche"

[lib]
crate-type = [ "cdylib" ]

[build-dependencies]
bindgen = "*"
csbindgen = "*"

[features]
android = []